version: '2.0'
services:

 #PHP Service
  app:
   build:
      context: .
      dockerfile: Dockerfile
   image: cloudsigma.com/php
   container_name: app
   restart: unless-stopped
   tty: true
   environment:
    SERVICE_NAME: app
    SERVICE_TAGS: dev
   volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini 
   working_dir: /var/www/html/
   networks:
    - app-network

  #Nginx Service
  webserver:
   image: nginx:alpine
   container_name: webserver
   restart: unless-stopped
   tty: true
   ports:
    - "80:80"
    - "443:443"
   networks:
    - app-network

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
     - "3306:3306"
    environment:
     MYSQL_DATABASE: zadanie_final
     MYSQL_ROOT_PASSWORD: password
     SERVICE_TAGS: dev
     SERVICE_NAME: mysql
    networks:
     - app-network

#Docker Networks
networks:
  app-network:
   driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
